apiVersion: v1
kind: Service
metadata:
  name: todo-api
  namespace: default
  labels:
    app: todo-api
spec:
  type: ClusterIP
  selector:
    app: todo-api
  ports:
  - name: http
    port: 80
    targetPort: 3000
    protocol: TCP
  sessionAffinity: None

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: todo-api
  namespace: default
  labels:
    app: todo-api

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-config
  namespace: default
  labels:
    app: todo-api
data:
  db_host: "postgres.default.svc.cluster.local"
  db_port: "5432"
  db_name: "tododb"
  environment: "production"

---
apiVersion: v1
kind: Secret
metadata:
  name: todo-secrets
  namespace: default
  labels:
    app: todo-api
type: Opaque
stringData:
  db_user: "todouser"
  db_password: "todopass"

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: todo-api-pdb
  namespace: default
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: todo-api

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: todo-api-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: todo-api
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
      - type: Percent
        value: 100
        periodSeconds: 30
      - type: Pods
        value: 2
        periodSeconds: 60
      selectPolicy: Max

